homeassistant:
  name: !secret sitename
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: !env_var TZ

http:
  ssl_certificate: /config/nathan-nathan.home-chain.pem
  ssl_key: /run/secrets/hass_key
  server_port: 4443

logger:
  default: info
  # logs:
  #   homeassistant.components.yamaha: critical
  #   custom_components.my_integration: critical

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
    # Text to speech
    tts:
      - platform: google_translate
    
    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

  
  