homeassistant:
  name: !secret sitename
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: !env_var TZ

http:
  ssl_certificate: /run/secrets/hass_cert
  ssl_key: /run/secrets/hass_key
  server_port: 4443

logger:
  default: info
  # logs:
    # homeassistant.components.mqtt: debug

mqtt:
  - sensor: !include_dir_list site/mqtt

recorder:
  db_url: !secret db_url

# want to have history graphs
history:

notify:
  !include site/notification.yaml

frontend:
  themes:
    default:
      primary-color: "#005f6a"
      modes:
        light:
          accent-color: "#6a0a00"
        dark:
          accent-color: "#6a0a00"

# own fields
input_number:
  bbiq_grill1_temperature:
    name: BBiQ Ziel°C Grill
    unit_of_measurement: "°C"
    initial: 160
    min: 100
    max: 300
    step: 5
    mode: slider
    icon: mdi:thermometer-lines
  bbiq_grill1_tolerance:
    name: BBiQ +/-°C Grill
    unit_of_measurement: "°C"
    initial: 10
    min: 0
    max: 20
    step: 1
    mode: box
    icon: mdi:delta

input_boolean:
  bbiq_grill1_surveillance:
    name: BBiQ Grill überwachen
    icon: mdi:thermometer-alert
  bbiq_meat1_surveillance:
    name: BBiQ Fleisch1 überwachen
    icon: mdi:thermometer-alert
  bbiq_meat2_surveillance:
    name: BBiQ Fleisch2 überwachen
    icon: mdi:thermometer-alert
  bbiq_meat3_surveillance:
    name: BBiQ Fleisch3 überwachen
    icon: mdi:thermometer-alert

# groups
binary_sensor groups: !include site/binary_groups.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
automation smokesensors: !include site/auto_smokesensors.yaml
automation tablets: !include site/auto_tablets.yaml
automation bbiq: !include site/auto_bbiq.yaml
#script: !include site/scripts.yaml
#scene: !include site/scenes.yaml

# this is needed if default_config is removed
my:
mobile_app:
bluetooth:
input_datetime:
input_select:
input_button:
input_text:
timer:
counter:
schedule:
  