homeassistant:
  name: !secret sitename
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: !env_var TZ

http:
  ssl_certificate: /run/secrets/hass_cert
  ssl_key: /run/secrets/hass_key
  server_port: 4443

logger:
  default: info
  # logs:
    # homeassistant.components.mqtt: debug

mqtt:
  - sensor: !include_dir_list site/mqtt

recorder:
  db_url: !secret db_url

frontend:
  themes:
    default:
      primary-color: "#005f6a"
      modes:
        light:
          accent-color: "#6a0a00"
        dark:
          accent-color: "#6a0a00"

# groups
binary_sensor groups: !include site/binary_groups.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
automation smokesensors: !include site/auto_smokesensors.yaml
#script: !include site/scripts.yaml
#scene: !include site/scenes.yaml

# this is needed if default_config is removed
my:
mobile_app:
bluetooth:
input_datetime:
input_select:
input_number:
input_boolean:
input_button:
input_text:
timer:
counter:
schedule:
  