homeassistant:
  name: !secret sitename
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  time_zone: !env_var TZ

http:
  ssl_certificate: /run/secrets/hass_cert
  ssl_key: /run/secrets/hass_key
  server_port: 4443

logger:
  default: info
  # logs:
    # homeassistant.components.mqtt: debug

mqtt:
  sensor: !include_dir_list site/mqtt


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:   
    group: !include site/groups.yaml
    automation: !include site/automations.yaml
    script: !include site/scripts.yaml
    scene: !include site/scenes.yaml

  
  