views:
  - title: Home
    icon: mdi:home
    badges: []
    cards:
      - show_current: true
        show_forecast: false
        type: weather-forecast
        entity: weather.forecast_home
        forecast_type: hourly
      - type: horizontal-stack
        cards:
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            entity: lock.haustuer_hausschloss_lock
            name: Haustür
            hold_action:
              action: none
          - show_name: true
            show_icon: true
            show_state: true
            type: glance
            entities:
              - entity: sensor.wohnzimmer_rauchwohnen_temperature_air
              - entity: sensor.julinzimmer_rauchjulian_temperature_air
              - entity: sensor.flur_rauchflur_temperature_air
              - entity: sensor.schlafzimmer_rauchschlafen_temperature_air
            columns: 2
            state_color: true
            title: Temperaturen
      - type: conditional
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity: switch.stecker3
                state: >-
                  {{ true if (now().month == 12 and now().day >= 24) else false
                  }}
              - condition: state
                entity: switch.stecker3
                state: >-
                  {{ true if (now().month == 1 and now().day <= 10) else false
                  }}
        card:
          type: button
          show_name: true
          show_icon: true
          tap_action:
            action: toggle
          entity: switch.stecker3
          icon: mdi:forest-outline
          name: Christbaum
  - title: Batterien
    path: batterien
    icon: mdi:battery-heart-variant
    type: sidebar
    badges: []
    cards:
      - type: entity-filter
        entities:
          - binary_sensor.fenstersensor_wcgast_contact
        conditions:
          - condition: state
            state: 'on'
        name: '!!! Offen !!!'
        show_empty: false
        show_header_toggle: false
      - type: tile
        entity: sensor.tablet1_batterie
        tap_action:
          action: call-service
          service: ''
          target: {}
        state_content:
          - state
          - last-changed
      - type: tile
        tap_action:
          action: call-service
          service: ''
          target: {}
        state_content:
          - state
          - last-changed
        entity: sensor.fenstersensor_wcgast_battery
      - type: tile
        entity: sensor.haustuer_hausschloss_battery_level
        state_content:
          - state
          - last-changed
  - title: Grill
    path: grill
    icon: mdi:grill
    cards:
      - square: false
        type: grid
        cards:
          - type: tile
            entity: sensor.bbiq_home_sensor_bbiq_battery
            show_entity_picture: false
            name: Akku
          - type: tile
            entity: sensor.bbiq_home_sensor_wifi_signal
            show_entity_picture: false
            hide_state: true
            color: black
            name: Wifi Signal
          - type: conditional
            conditions:
              - condition: state
                entity: sensor.bbiq_home_sensor_temperature1
                state_not: unavailable
            card:
              type: gauge
              entity: sensor.bbiq_home_sensor_temperature1
              min: 0
              max: 300
              severity:
                green: 0
                yellow: 200
                red: 100
              name: Grilltemperatur
          - type: conditional
            conditions:
              - condition: state
                entity: sensor.bbiq_home_sensor_temperature1
                state: unavailable
            card:
              type: markdown
              content: _Bitte einstecken_
              title: Kein Grillsensor
          - type: conditional
            conditions:
              - condition: state
                entity: sensor.bbiq_home_sensor_temperature2
                state_not: unavailable
            card:
              type: gauge
              entity: sensor.bbiq_home_sensor_temperature2
              min: 0
              max: 300
              severity:
                green: 0
                yellow: 200
                red: 100
              name: Gargrad 1
          - type: conditional
            conditions:
              - condition: state
                entity: sensor.bbiq_home_sensor_temperature2
                state: unavailable
            card:
              type: markdown
              content: _Bitte einstecken_
              title: Kein Fleisch- sensor1
          - type: conditional
            conditions:
              - condition: state
                entity: sensor.bbiq_home_sensor_temperature3
                state_not: unavailable
            card:
              type: gauge
              entity: sensor.bbiq_home_sensor_temperature3
              min: 0
              max: 300
              severity:
                green: 0
                yellow: 200
                red: 100
              name: Gargrad 2
          - type: conditional
            conditions:
              - condition: state
                entity: sensor.bbiq_home_sensor_temperature3
                state: unavailable
            card:
              type: markdown
              content: _Bitte einstecken_
              title: Kein Fleisch- sensor2
          - type: conditional
            conditions:
              - condition: state
                entity: sensor.bbiq_home_sensor_temperature4
                state_not: unavailable
            card:
              type: gauge
              entity: sensor.bbiq_home_sensor_temperature4
              min: 0
              max: 300
              severity:
                green: 0
                yellow: 200
                red: 100
              name: Gargrad 3
          - type: conditional
            conditions:
              - condition: state
                entity: sensor.bbiq_home_sensor_temperature4
                state: unavailable
            card:
              type: markdown
              content: _Bitte einstecken_
              title: Kein Fleisch- sensor3
        columns: 2
      - square: false
        type: grid
        cards:
          - type: entity
            entity: input_number.bbiq_grill1_temperature
          - type: entity
            entity: input_number.bbiq_grill1_tolerance
          - type: entity
            entity: input_boolean.bbiq_grill1_surveillance
        columns: 3
      - type: history-graph
        entities:
          - entity: sensor.bbiq_home_sensor_temperature1
        title: BBiQ Grillkontrolle
        hours_to_show: 1
        max_y_axis: 300
        min_y_axis: 80
      - type: history-graph
        entities:
          - entity: sensor.bbiq_home_sensor_temperature2
          - entity: sensor.bbiq_home_sensor_temperature3
          - entity: sensor.bbiq_home_sensor_temperature4
        hours_to_show: 1
        title: BBiQ Fleischkontrolle
        min_y_axis: 50
        max_y_axis: 80
        logarithmic_scale: false
        fit_y_data: true
  - title: Fitnessraum
    path: fitnessraum
    icon: mdi:weight-lifter
    cards:
      - type: light
        entity: light.led_panel
title: Rederlechner Zuhause
