version: "3.6"

###
# Build with
# NATHAN_BUILD_VERSION="0.1.1" docker-compose build --force-rm --pull

networks:
  home-net:
    name: home-net
    driver: bridge

services:
    #assistant:
    #    restart: always
    #    image: "nathanhome/assistant:${NATHAN_BUILD_VERSION}"
    #    build:
    #        context: ./images/docker-hass-io
    #        args:
    #            build_version: "${NATHAN_BUILD_VERSION}"
    #    ports:
    #        - 443:4143
    #    environment:
    #        TZ: "Europe/Berlin"
    #        MQTTS_USER: /var/run/mqtts_user 
    #        MQTTS_PASSWORD: /var/run/mqtts_password
    #        HOMEASSI_KEY: /var/run/homeassi_key
    #        # - PUID=1000
    #        # - PGID=1000
    #        #- UMASK=007
    #        #- PACKAGES=iputils
    #    volumes:
    #        - "/home/homedock/.nathan/homeassistant:/config"
    #        - "/etc/localtime:/etc/localtime:ro"
    #        # - "/PATH_TO_YOUR_CONFIG/docker/run:/etc/services.d/home-assistant/run"
    #    networks:
    #        - home-net
    #    #links:
        #    - "mosquitto:mqtts.home"

    mosquitto:
      #restart: always
      image: "nathanhome/mosquitto:${NATHAN_MQTT_VERSION}"
      build:
        context: ./images/docker-mosquitto
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
        - /home/mosquitto/.nathan/data:/mosquitto/data
        - /home/mosquitto/.nathan/log:/mosquitto/log
        - /home/mosquitto/.nathan/config:/mosquitto/config
      networks:
        - home-net
      secrets:
        - mqtts_key
        - mqtts_passwd

# TODO: Password still in clear text on docker host
secrets:
    mqtts_key:
      file: /home/digital/.nathan/mosquitto/nathan-mqtts.home.key
    mqtts_passwd:
      file: /home/digital/.nathan/mosquitto/mosquitto.passwd
    hass_key:
      file: /home/digital/.nathan/homeassist/nathan-pi-home.home.key
    hass_mqtts_pass:
      file: /home/digital/.nathan/homeassist/mqtts_pass.txt

