version: "3.6"

###
# Build with
# NATHAN_BUILD_VERSION="0.1.1" docker-compose build --force-rm --pull

networks:
  home-net:
    name: home-net
    driver: bridge

services:
    assistant:
      restart: unless-stopped
      image: "nathanhome/assistant:${NATHAN_HASS_VERSION}"
      build:
        context: ./images/docker-hass-io
      group_add:
        - ${NATHAN_GROUP}
        - ${BLUETOOTH_GROUP}
      ports:
        - 443:4443
      environment:
        - TZ=Europe/Berlin
        - PUID=1884
        - PGID=1884
        - UMASK=007
        - PACKAGES=iputils
        - HASS_MQTT_HOST=mqbroker
        - HASS_MQTT_PORT=8883
      volumes:
        # this is a mounting workaround as homeassistant expects secrets file under
        # /config/secrets.yaml, which we deviated in docker image to docker-compose
        # secrets file by soft link
        - "/home/assistant/.nathan/config/configuration.yaml:/config/configuration.yaml"
        - "/home/assistant/.nathan/config/.cloud:/config/.cloud"
        - "/home/assistant/.nathan/config/.storage:/config/.storage"
        - "/home/assistant/.nathan/config/blueprints:/config/blueprints"
        - "/home/assistant/.nathan/config/site:/config/site"
        - "/home/assistant/.nathan/config/tts:/config/tts"
        - "/etc/localtime:/etc/localtime:ro"
        - "/run/dbus:/run/dbus:ro"         # bluetooth non-priviledged, non-host network 
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      networks:
        - home-net
      security_opt:  
        - no-new-privileges
      secrets:
        - hass_key
        - hass_cert
        - hass_secrets
        - hass_mqtt_trust
        - hass_mqtt_cert
        - hass_mqtt_key
      depends_on:
        - mqbroker
        - homedb

    homedb:
      restart: unless-stopped
      # no modification for standdard db image
      image: "mariadb:${NATHAN_MARIADB_VERSION}"
      user: 1887:1887
      group_add:
        - ${NATHAN_GROUP}
      ports:
        - "3306:3306"
      environment:
        - MARIADB_ROOT_USER=homeroot
        - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/homedb_rootpass
        - MARIADB_DATABASE=hassdb
        - MARIADB_USER=assistant
        - MARIADB_PASSWORD_FILE=/run/secrets/homedb_hasspass
      volumes:
        - /home/homedb/.nathan/data:/var/lib/mysql
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      networks:
        - home-net
      secrets:
        - homedb_rootpass
        - homedb_hasspass

    mqbroker:
      restart: unless-stopped
      image: "nathanhome/mosquitto:${NATHAN_MQTT_VERSION}"
      build:
        context: ./images/docker-mosquitto
      group_add:
        - ${NATHAN_GROUP}
      ports:
        - "8883:8883"
        - "1883:1883"
        # don't expose mqtt access: - "1883:1883"
      volumes:
        - /home/mosquitto/.nathan/data:/mosquitto/data
        - /home/mosquitto/.nathan/config:/mosquitto/config
        - /var/log/mqbroker:/mosquitto/log
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      networks:
        - home-net
      secrets:
        - mqbroker_key
        - mqbroker_cert
        - mqbroker_ca
        - mqbroker_passwd

    zwgate:
      restart: unless-stopped
      image: "nathanhome/zwavejs:${NATHAN_ZWAVEJS_VERSION}"
      build:
        context: ./images/docker-zwavejs
      user: 1885:1885
      group_add:
        - ${NATHAN_GROUP}
        - ${DIALOUT_GROUP}
      tty: true
      stop_signal: SIGINT
      devices:
          # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
          # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
          - '/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave'
      volumes:
          - zwave-config:/usr/src/app/store
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      # Or by using local folder
      # - ./store:/usr/src/app/store
      ports:
          - '8091:8091' # port for web interface
          - '3000:3000' # port for Z-Wave JS websocket server
      volumes:
        - /home/zwgate/.nathan/data:/usr/src/app/store
        - /home/zwgate/.nathan/config:/usr/src/app/config
        - /var/log/zwgate:/usr/src/app/logs
        # - /mnt/nathan/zwgate/backup:/usr/src/app/backup
      environment:
        - TZ=Europe/Berlin
        - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
        - ZWAVEJS_LOGS_DIR=/usr/src/app/logs
        # - BACKUPS_DIR=/usr/src/app/backup
        - MQTT_NAME=mqbroker
        - MQTT_HOST=mqtts://mqbroker
        - MQTT_PORT=88
        - HTTPS=1
        - SSL_CERTIFICATE=/run/secrets/zwgate_cert
        - SSL_KEY=/run/secrets/zwgate_key
        - UID_DISCOVERY_PREFIX=zwgate_
      networks:
        - home-net
      secrets:
        - zwgate_key
        - zwgate_cert
        - zwgate_mqtt_ca
        - zwgate_mqtt_key
        - zwgate_mqtt_cert
        - zwgate_secrets

    zigate:
      restart: unless-stopped
      image: "koenkk/zigbee2mqtt:${NATHAN_ZIGBEE2MQTT_VERSION}"
      user: 1886:1886
      group_add:
        - ${NATHAN_GROUP}
        - ${TTY_GROUP}
      volumes:
        - /home/zigate/.nathan/data:/app/data
        - /dev/zigbee:/dev/zigbee
        - /run/udev:/run/udev:ro
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      ports:
        - 8092:8080
      environment:
        - TZ=Europe/Berlin
      networks:
        - home-net
      secrets:
        - zigate_key
        - zigate_cert
        - zigate_trust
        - zigate_mqtt_cert
        - zigate_mqtt_key
        - zigate_secrets.yaml

    solarspot:
      profiles:
        - donotstart
      restart: unless-stopped
      image: "nathanhome/sbfspot:${NATHAN_SBFSPOT_VERSION}"
      build:
        context: ./images/docker-sbfspot
        args:
          - user=solar
          - group=solar
          - uid=1888
          - pid=1888
      user: 1888:1888
      group_add:
        - ${NATHAN_GROUP}
        - ${BLUETOOTH_GROUP}
      tty: true
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/run/dbus:/run/dbus:ro"
      environment:
        - TZ=Europe/Berlin
        - ENABLE_SBFSPOT=1
        - SBFSPOT_INTERVAL=300
        - ENABLE_SBFSPOT_UPLOAD=0
        - DB_STORAGE=mariadb
        - CSV_STORAGE=0
        - MQTT_ENABLE=1
        - QUIET=0
        - SBFSPOT_ARGS="-d0 -v2"
        - INIT_DB=0
      networks:
        - home-net

# TODO: Password still in clear text on docker host
secrets:
    mqbroker_key:
      file: /home/digital/.nathan/mosquitto/mqbroker-202401.key
    mqbroker_cert:
      file: /home/digital/.nathan/mosquitto/mqbroker-202401.pem
    mqbroker_ca:
      file: /home/digital/.nathan/mosquitto/mqbroker-trust-202401.pem
    mqbroker_passwd:
      file: /home/digital/.nathan/mosquitto/mosquitto.passwd
    hass_key:
      file: /home/digital/.nathan/common/nathan-202401.key
    hass_cert:
      file: /home/digital/.nathan/common/nathan-202401.pem
    hass_mqtt_trust:
      file: /home/digital/.nathan/homeassistant/homeassistant-trust-202401.pem
    hass_mqtt_cert:
      file: /home/digital/.nathan/homeassistant/homeassistant-client-202401.pem
    hass_mqtt_key:
      file: /home/digital/.nathan/homeassistant/homeassistant-client-202401.key
    hass_secrets:
      file: /home/digital/.nathan/homeassistant/secrets.yaml
    zigate_key:
      file: /home/digital/.nathan/common/nathan-202401.key
    zigate_cert:
      file: /home/digital/.nathan/common/nathan-202401.pem
    zigate_trust:
      file: /home/digital/.nathan/zigate/zigate-trust-202401.pem
    zigate_mqtt_key:
      file: /home/digital/.nathan/zigate/zigate-client-202401.key
    zigate_mqtt_cert:
      file: /home/digital/.nathan/zigate/zigate-client-202401.pem
    zigate_secrets.yaml:
      file: /home/digital/.nathan/zigate/secrets.yaml
    zwgate_key:
      file: /home/digital/.nathan/common/nathan-202401.key
    zwgate_cert:
      file: /home/digital/.nathan/common/nathan-202401.pem
    zwgate_mqtt_ca:
      file: /home/digital/.nathan/zwgate/zwgate-trust-202401.pem
    zwgate_mqtt_key:
      file: /home/digital/.nathan/zwgate/zwgate-client-202401.key
    zwgate_mqtt_cert:
      file: /home/digital/.nathan/zwgate/zwgate-client-202401.pem
    zwgate_secrets:
      file: /home/digital/.nathan/zwgate/secrets.txt
    homedb_rootpass:
      file: /home/digital/.nathan/homedb/maria.pwd
    homedb_hasspass:
      file: /home/digital/.nathan/homedb/hassdb.pwd



