version: "3.6"

###
# Build with
# NATHAN_BUILD_VERSION="0.1.1" docker-compose build --force-rm --pull

networks:
  home-net:
    name: home-net
    driver: bridge

services:
    assistant:
    #    restart: always
      image: "nathanhome/assistant:${NATHAN_HASS_VERSION}"
      build:
        context: ./images/docker-hass-io
      ports:
        - 443:4443
      environment:
        - TZ="Europe/Berlin"
        - PUID=1884
        - PGID=1884
        - UMASK=007
        - PACKAGES=iputils
      volumes:
        - "/home/assistant/.nathan/config:/config"
        - "/run/secrets/hass_secrets:/config/secrets.yaml"
        - "/etc/localtime:/etc/localtime:ro"
      networks:
        - home-net
      security_opt:  
        - no-new-privileges

    mqbroker:
      #restart: always
      image: "nathanhome/mosquitto:${NATHAN_MQTT_VERSION}"
      build:
        context: ./images/docker-mosquitto
      ports:
        - "8883:8883"
        # don't expose mqtt access: - "1883:1883"
      volumes:
        - /home/mosquitto/.nathan/data:/mosquitto/data
        - /home/mosquitto/.nathan/log:/mosquitto/log
        - /home/mosquitto/.nathan/config:/mosquitto/config
      networks:
        - home-net
      secrets:
        - mqbroker_key
        - mqbroker_passwd

# TODO: Password still in clear text on docker host
secrets:
    mqbroker_key:
      file: /home/digital/.nathan/mosquitto/nathan-mqbroker.nathan.home.key
    mqbroker_passwd:
      file: /home/digital/.nathan/mosquitto/mosquitto.passwd
    hass_key:
      file: /home/digital/.nathan/homeassist/nathan-nathan.home.key
    hass_secrets:
      file: /home/digital/.nathan/homeassist/secrets.yaml

