= NATHAN home automation

Distributed, secure container installation of MQTT broker, HomeAssistant, ZWave
and solar control (sbfspot).

== Mosquitto setup

.Non-root user
To run Eclipse Mosquitto MQTT broker as non-root, you need to create a system user
`mosquitto` _with UID `1883`_ on host level. The corresponding user in container is
created automatically.

.File system structure
----
/home/mosquitto
  + .nathan
    + config
    | - mosquitto.conf                # external configuration
    | - nathan-mqtts.home-chain.pem   # certificate trust chain
    | - nathan-mqtts.home.pem         # mqtts server certificate
    + data
    + log
    | - mosquitto.log                 # mosquitto-written log

/home/<docker-compose-user>           # credentials
  + .nathan/mosquitto                 
    - mosquitto.passwd                # user/password of client broker users
    - nathan-mqtts.home.pem           # private server key
----

== Certificate refresh

=== Services

Before refreshing certificates, back up the current certificates and (re)move
the toplevel config directory under the `digital` user:

1. Execute `refresh-certs.sh`

2. Copy the following files and driectoriesfrom previous setup
+
----
~digital/.nathan/homeassistant/secrets.yaml
~digital/.nathan/zigate/secrets.yaml
~digital/.nathan/zwgate/secrets.txt
~digital/.nathan/homedb

touch mosquitto.passwd
----

3. Copy the nathanca-xxx.cer file to NAS for distribution to the private devices

4. Change the names of the secrets in `docker-compose.yaml` to the names of the newly
   generated files.

5. Start with `controller/compose.sh up -d` 

=== Clients

.Android

- Send certificate by email

- Save attached certificate to `Downloads` folder

- Go to settings, search for "Certificate"

- Install "CA-Certficiate" from `Downloads` folder

.Fully Kiosk

- Open remote Admin page:
  http://<device>:2323

- Upload via "manage Files to Downloads"

- Go to settings, search for "Certificate"

- Install "CA-Certficiate" from `Downloads` folder

