FROM eclipse-mosquitto:2.0.18-openssl
ARG nathan_user


LABEL version="2.0-2" \
      maintainer="rbe-git@t-online.de" \
      description="Mosquitto broker configured for NATHAN home automation"

# config is always part of the immutable image
#COPY mosquitto.conf  /mosquitto/config/mosquitto.conf

