###
# automation actions for charging and activation of control tablets
- alias: "Tablet1 start loading"
  id: "tablet1_charge_autostart"
  trigger:
    - platform: state
      entity_id:
        - sensor.tablet1_batterie
  condition:
    and:
      - condition: numeric_state
        entity_id: sensor.tablet1_batterie
        below: 20
      - condition: state
        entity_id: binary_sensor.tablet1_eingesteckt
        state: "off"
  action:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.kioskcharger1

- alias: "Tablet1 stop loading"
  id: "tablet1_charge_autostop"
  trigger:
    - platform: state
      entity_id:
        - sensor.tablet1_batterie
  condition:
    and:
      - condition: numeric_state
        entity_id: sensor.tablet1_batterie
        above: 80
      - condition: state
        entity_id: binary_sensor.tablet1_eingesteckt
        state: "on"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.kioskcharger1

###
# Show open notification on tablet fullscreen
- alias: "Tablet gastwc window open"
  id: "tablet1_guest_wcgast_open"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.fenstersensor_wcgast_contact
      to: "on"
  action:
    # alias: "Set fully kiosk screensaver to alarm"
    - service: switch.turn_off
      target:
        entity_id:
          - switch.tablet1_bildschirmschoner
    - service: fully_kiosk.set_config
      data:
        key: "screensaverWallpaperURL"
        value: "https://nathan/local/gastwcopen576.gif"
      target:
        device_id:
          - 73bbc85f6c81ba43cd3f950a62e8f2a9
    - service: fully_kiosk.set_config
      data:
        key: "screensaverBrightness"
        value: "95"
      target:
        device_id:
          - 73bbc85f6c81ba43cd3f950a62e8f2a9
    - service: switch.turn_on
      target:
        entity_id:
          - switch.tablet1_bildschirmschoner

###
# Escalate if window stays open for more than interval minutes
- alias: "Tablet gastwc window open alarm"
  id: "tablet1_guest_wcgast_alarm"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.fenstersensor_wcgast_contact
      to: "on"
      for:
        minutes: 17
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.tablet1_bildschirmschoner
    - service: fully_kiosk.set_config
      data:
        key: "screensaverWallpaperURL"
        value: "https://nathan/local/gastwcalarm576.gif"
      target:
        device_id: 73bbc85f6c81ba43cd3f950a62e8f2a9
    - service: fully_kiosk.set_config
      data:
        key: "screensaverBrightness"
        value: "95"
      target:
        device_id: 73bbc85f6c81ba43cd3f950a62e8f2a9
    - service: switch.turn_on
      target:
        entity_id:
          - switch.tablet1_bildschirmschoner

###
# Reset fullscreen screensaver to normal on window close
- alias: "Tablet gastwc window closed"
  id: "tablet1_wcgast_closed"
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.fenstersensor_wcgast_contact
      to: "off"
  action:
    # alias: "Black out fully kiosk screensaver"
    - service: switch.turn_off
      target:
        entity_id:
          - switch.tablet1_bildschirmschoner
    - service: fully_kiosk.set_config
      data:
        key: "screensaverWallpaperURL"
        value: "fully://color#000000"
      target:
        device_id: 73bbc85f6c81ba43cd3f950a62e8f2a9
    - service: fully_kiosk.set_config
      data:
        key: "screensaverBrightness"
        value: "0"
      target:
        device_id: 73bbc85f6c81ba43cd3f950a62e8f2a9
