###
# automation actions for charging and activation of control tablets
- alias: "Tablet1 start loading"
  id: "tablet1_charge_autostart"
  trigger:
    - platform: state
      entity_id:
        - sensor.tablet1_batterie
  condition:
    and:
      - condition: numeric_state
        entity_id: sensor.tablet1_batterie
        below: 20
      - condition: state
        entity_id: binary_sensor.tablet1_eingesteckt
        state: "off"
  action:
    - service: switch.turn_on
      target:
        entity_id:
          - switch.kioskcharger1


- alias: "Tablet1 stop loading"
  id: "tablet1_charge_autostop"
  trigger:
    - platform: state
      entity_id:
        - sensor.tablet1_batterie
  condition:
    and:
      - condition: numeric_state
        entity_id: sensor.tablet1_batterie
        above: 80
      - condition: state
        entity_id: binary_sensor.tablet1_eingesteckt
        state: "on"
  action:
    - service: switch.turn_off
      target:
        entity_id:
          - switch.kioskcharger1
